# Generated by Django 5.1 on 2024-09-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='bio',
            new_name='balance',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
