# Generated by Django 5.1 on 2024-09-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_rename_bio_buyer_balance_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField()),
                ('age_limited', models.BooleanField(default=False)),
                ('buyer', models.ManyToManyField(related_name='buers', to='task1.buyer')),
            ],
        ),
    ]
